services:

  redmine:
    build: .
    container_name: redmine
    restart: unless-stopped
    ports:
      - "<HOST_IP>:HOST_PORT:3000"
    environment:
      REDMINE_DB_POSTGRES: redmine_db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: password
      REDMINE_SECRET_KEY_BASE: long_string
    depends_on:
      - redmine_db
      - redis
    volumes:
      - ./redmine_persistent/redmine_data:/usr/src/redmine/files
      - ./redmine_persistent/configuration.yml:/usr/src/redmine/config/configuration.yml


  redmine_worker:
    build: .
    container_name: redmine_worker
    restart: unless-stopped
    command: ["rake", "sidekiq:start"]
    environment:
      REDMINE_DB_POSTGRES: redmine_db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: password
      REDMINE_SECRET_KEY_BASE: long_string
    depends_on:
      - redmine_db
      - redis
    volumes:
      - ./redmine_persistent/redmine_data:/usr/src/redmine/files
      - ./redmine_persistent/configuration.yml:/usr/src/redmine/config/configuration.yml


  redmine_db:
    image: postgres:15
    container_name: redmine_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redmine
    volumes:
      - ./redmine_persistent/postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7-alpine
    container_name: redmine_redis
    restart: unless-stopped
    volumes:
      - ./redmine_persistent/redis_data:/data
